server/fairy.py

This relies on gbtami/Fairy-Stockfish#11 to be merged first.

Move insufficient material handling to pyffish

---

client/chess.ts
client/editor.ts

This also adds back the flipped pawn piece to the piece row.
I created a new variantFenChange method in case other variants also need FEN changes in the future.

Fix issue with makruk F and M~ in editor

---

static/images/pieces/shogi/ctw/0RY.svg

Haven't done a request before hopefully I did it right. I only did it on the wood dragon this is me just testing.

Removed extra dragon 0RY.svg

---

client/roundCtrl.ts

The behaviour I propose at the moment is having the setup sound represents Red's finish of the setup phase for both players. We can discuss things further here.

Janggi setup sound

---

client/analysis.ts
client/analysisCtrl.ts
client/chess.ts
client/info.ts
client/round.ts
client/roundCtrl.ts
client/settings.ts
server/fairy.py
server/game.py
server/utils.py
server/wsr.py
static/site.css

Partial implementation for #172. This relies on [ianfab/Fairy-Stockfish#114](https://github.com/ianfab/Fairy-Stockfish/pull/114) to be merged first.

Manual counting

---

client/movelist.ts
static/site.css

Update for both dark and light themes with more lichess colors and styling (buttons, icons, tables, etc.). Some preview images: https://imgur.com/a/hYXcbad

Theme update

---

static/site.css

I used lichess as reference. solves #335 
Would you be kind to add the label 'hacktoberfest-accepted' to this PR?

change default scrollbar style

---

client/analysisCtrl.ts
client/chat.ts
client/roundCtrl.ts

This adds a checkbox on top of the chat to disable chatting. Maybe the descriptive strings can be improved.

Add chat checkbox, close #162

---

client/chat.ts

Followup to #396, to improve aesthetics.

Move checkbox to title of chat room

---

client/analysisCtrl.ts
client/chat.ts
client/roundCtrl.ts

Emulates Lichess behaviour.
However when disabling the chat, the header moves a bit. This needs a fix

Checkbox hides/shows chat

---

client/analysis.ts
client/invite.ts
client/lobby.ts
client/profile.ts
client/round.ts
client/view.ts
server/misc.py

This PR uses the values taken from [the Lichess code](https://github.com/ornicar/lila/blob/master/ui/lobby/src/setup.ts) as possible minutes and increments. Fixes #400

Lichess values for setting minutes and increments

---

static/images/pieces/shogi/ctkw3d/0GI.svg
static/images/pieces/shogi/ctkw3d/0GY.svg
static/images/pieces/shogi/ctkw3d/0KA.svg
static/images/pieces/shogi/ctkw3d/0NY.svg
static/images/pieces/shogi/ctkw3d/0TO.svg

When fixing the .001 size difference

Forgot to center these

---

client/analysisCtrl.ts
client/boardSettings.ts
client/chart.ts
client/chess.ts
client/editor.ts
client/games.ts
client/lobby.ts
client/pieces.ts
client/pocket.ts
client/profile.ts
client/promotion.ts
client/roundCtrl.ts

The variant class system has been deprecated and should be replaced by variant objects for a long time. This PR actually removes it and entirely replaces its usage with equivalent statements.

Remove variant class system

---

static/docs/tr/dobutsu.md

Translated the title of rules section in dobutsu for test purpose

Dobutsu-Rules-translation.md

---

static/news/The Winner Is Tasshaq.md

Update The Winner Is Tasshaq.md

---

static/docs/capahouse960.md
static/docs/dobutsu.md
static/docs/grandhouse.md
static/docs/kyotoshogi.md
static/docs/orda.md
static/docs/shinobi.md
static/docs/shouse.md
static/docs/synochess.md
static/docs/xiangqi.md

https://github.com/gbtami/pychess-variants/issues/532#issue-926559508
Updated all the .mds with typos except sittuyin since it's already correct! :)

Typo correction

---

static/docs/capablanca.md
static/docs/gothic.md

I don't know if you wrote "**seiwaran**" on purpose…

Spelling correction

---

static/docs/es/chess.md
static/docs/es/grand.md
static/docs/es/placement.md

I just fixed a couple of silly typos I introduced in the Spanish translations. Sorry 🙏 🙃

Fix typos in spanish translations

---

client/zen.ts
static/site.css

Fixed setting that wasn't updating its value when using the zenMode button to disable it.
I also included a minor CSS fix to make the button look ok in dark mode.

Fixes in zen mode

---

client/roundCtrl.ts
server/wsr.py

https://github.com/gbtami/pychess-variants/issues/232

Implement view rematch button

---

static/docs/faq.md
static/faq.css

Improve FAQ page

---

static/docs/faq.md

<details><summary>Changes made:</summary>
- Italic removed from questions
- Spell FAQ in long form
Like on Lichess.</details>

Make FAQ page look more Lichess like

---

client/analysisCtrl.ts
client/roundCtrl.ts

https://github.com/gbtami/chessgroundx/pull/18

Fix issues with premoving castling and shako pawn double step

---

static/site.css

Added max-width to the header for bigger screens

header max width

---

static/site.css
static/tournament.css

Would fix https://github.com/gbtami/pychess-variants/issues/580

Improve Join/withdraw button

---

static/site.css

It's not 100% same as on lichess.

Add hover effects to login button 

---

client/stats.ts
server/game_api.py
server/routes.py
server/server.py

- Add switching the plot to linear scale
- Add counting only human games

Add more options to the stats page

---

static/site.css

Santa Came

---

tests/client_stresstest.py

https://deepsource.io/gh/gbtami/pychess-variants/run/9fb302be-77fb-4475-8e6c-f3e1655d74eb/python/PY-W2000

Remove Unused import from const

---

client/movelist.ts

added spacing for better reading.

FORMATTING Update movelist.ts

---

client/messages.ts
client/movelist.ts
server/game.py
server/utils.py
static/site.css

Add saving and displaying move time for rated games

---

client/analysisCtrl.ts
client/boardSettings.ts
client/document.ts
package.json
static/chessground.css

Need to merge [chessgroundx#36](https://github.com/gbtami/chessgroundx/pull/36) first.

Make required changes for Chessgroundx 9.3.0

---

client/games.ts
server/game_api.py
static/games.css

See #972 
- `/games` now shows titles of players in case they have one.
- `/games` now shows bot level of players in case they are a bot.

Make /games show bot level in case of a bot game

---

static/news/NNUE Everywhere.md

Update NNUE Everywhere.md

---

client/cgCtrl.ts
client/chess.ts
client/variantsIni.ts
server/const.py
server/fairy.py
variants.ini

This will apply to any Capablanca starts with the king on the e-file. Also applies to Capahouse.
Fixes #1035

Embassy Castling Fix

---

static/images/pieces/green/bS.svg
static/images/pieces/green/wS.svg
static/piece/makruk/makrukc.css

Cburnett (Thai elephants)

---

client/boardSettings.ts
client/roundCtrl.ts

Closes https://github.com/gbtami/pychess-variants/issues/1090

Option to disable confirmation dialog box when resigning a game.

---

static/lobby.css

Fix player and game counter overlapping on PLAY WITH AI button on mobile

---

static/features.css
static/site.css
templates/features.html

Add features page

---

static/docs/faq.js

Now, you can share this URL to anyone who is asking for Shatranj to be added:
https://www.pychess.org/faq#11 :D

Create links for FAQ questions

---

static/images/pieces/chak/maya/GD.svg
static/images/pieces/chak/maya/GJ.svg
static/images/pieces/chak/maya/GK.svg
static/images/pieces/chak/maya/GO.svg
static/images/pieces/chak/maya/GP.svg
static/images/pieces/chak/maya/GQ.svg
static/images/pieces/chak/maya/GR.svg
static/images/pieces/chak/maya/GS.svg
static/images/pieces/chak/maya/GV.svg
static/images/pieces/chak/maya/GW.svg
static/images/pieces/chak/maya/WD.svg
static/images/pieces/chak/maya/WJ.svg
static/images/pieces/chak/maya/WK.svg
static/images/pieces/chak/maya/WO.svg
static/images/pieces/chak/maya/WP.svg
static/images/pieces/chak/maya/WQ.svg
static/images/pieces/chak/maya/WR.svg
static/images/pieces/chak/maya/WS.svg
static/images/pieces/chak/maya/WV.svg
static/images/pieces/chak/maya/WW.svg

Chak Maya pieces

---

static/profile.css
static/site.css

Slight profile page improvements on smaller screen

---

static/site.css
templates/template.html

Improve import game function

---

static/site.css

Align search results

---

templates/features.html

* board editor
* translation source

Add links to features page

---

static/site.css

https://github.com/gbtami/pychess-variants/assets/126312812/b096b229-1863-4e6b-a57c-2d3e195aeafa

Board Settings Misaligned on Safari

---

static/site.css

Button padding specifications

---

static/tournament.css

Improve Join Button Color

---

static/404.css
templates/404.html

Refactor 404 page ui

---

static/group-colors.css
static/site.css
templates/variants.html

https://github.com/gbtami/pychess-variants/assets/126312812/76228351-a61a-4f14-91c7-765c64e80118

Add sidebar line hover effect

---

static/site.css

#1377 
https://github.com/gbtami/pychess-variants/assets/126312812/1a37c650-19fa-46b3-adc0-2721d041d6a9

Improve sidebar line hover effect

---

static/site.css

Change seeks table font 

---

client/chat.ts
client/lobby/layer1.ts
client/settingsView.ts

animated sliding pieces, discord icon, settings button
https://www.w3.org/WAI/tutorials/images/decorative/

Accessibility Changes

---

static/site.css
templates/blog.html
templates/videos.html

https://github.com/gbtami/pychess-variants/assets/126312812/4e435143-bb7c-4aae-b4ab-5253ab650aab

Extend sidebar hover line effect to blogs and videos

---

static/blogs.css
static/site.css

Expand blogs and move everything right

---

static/site.css

Before: 
https://github.com/gbtami/pychess-variants/assets/126312812/edf4f5c3-ece6-414b-9065-e8199e9c2b37
After:
https://github.com/gbtami/pychess-variants/assets/126312812/c3b910fe-82e4-4761-830c-ed0dadae7ca7

Fix table heading showing through during scroll

---

static/site.css

Set uniform blog dimensions

---

static/profile.css

Center profile game categories text

---

static/lobby.css
static/site.css

https://github.com/gbtami/pychess-variants/assets/126312812/64dd4afd-10c5-4227-bc8d-3002a2a28b3a

Make new game modal responsive

---

client/notifyView.ts
templates/404.html
templates/blogs.html

Fix 404 canvas, blog images, and notifications PR errors

---

static/layer-1.css
static/site.css

https://github.com/gbtami/pychess-variants/assets/126312812/5fa689b7-ad6f-4051-aa7f-6d20f494e95f
https://github.com/gbtami/pychess-variants/assets/126312812/9600a4af-f09d-486a-b931-4a7d1d5b6a68
https://github.com/gbtami/pychess-variants/assets/126312812/a3ec749f-caef-4f66-9112-ba6920bd4eaf
https://github.com/gbtami/pychess-variants/assets/126312812/f0fe03b4-636b-4d65-9eb6-cc9a615b6f5f
It could just be me thinking that the panels look very dull.

Increase vpanel contrast

---

static/docs/cannonshogi.md

I bascially re-explained everything to be simpler and sorted all necessary info to their respective sections. Feedback is welcome to improve though. 
NOTE: I just pasted the images in, so you may need to organise them into the appropriate folders. Sorry.
All g if you use the old images though.

Rewritten rules for cannonshogi.md

---

static/images/pieces/xiangqi/guided/black_pawn_b.svg
static/images/pieces/xiangqi/guided/red_pawn_b.svg

I tried out the Guided set on Pychess, but I found a problem, the Pawns on the opposing side point up rather than down, which was disorienting for me. (And can be for other players too)
This PR just includes the svgs needed to fix it.

Guided Xiangqi Set Pawn Fix

---

static/site.css

Header
- font-smoothing
Notifications
- remove bottom border
- remove hover effects
Settings
- extend dark mode dropdown color theme
- adjust spacing
- remove language x-scrollbar
- limit language section max height
All
- add shadow and rounded corners

improve header, notifications, and settings visually

---

static/tournaments.css

* align page title and calendar button
* make individual tournament names visible in dark mode

Improve tournament list

---

static/blogs/Late Summer Update.md

minor grammatical and spelling fixes

Update Late Summer Update.md

---

README.md
docker-compose.yaml

* Add documentation
* Provide default for DB authentication

Update docker setup

---

server/ai.py
server/game.py
server/pychess_global_app_state.py

Fixes https://github.com/gbtami/pychess-variants/issues/1637

Resume ai games

---

.github/workflows/ci.yml
client/lobby.ts
server/auto_pair.py
server/bot_api.py
server/bug/game_bug.py
server/const.py
server/game.py
server/index.py
server/lobby.py
server/pychess_global_app_state.py
server/server.py
server/user.py
server/utils.py
server/websocket_utils.py
server/wsl.py
server/wsr.py
static/lobby.css
tests/test_960_rematch.py
tests/test_corr_janggi_setup.py

Implement https://github.com/gbtami/pychess-variants/issues/1267

Auto pairing

---

client/variants.ts
server/puzzle.py

Add Manchu+ Puzzles

---

static/analysis.css

Align puzzle sliders with labels

---

static/blogs/Mid Autumn Festival.md
static/patron.css
static/round.css

Minor miscellaneous improvments

---

client/analysisCtrl.ts
client/bug/analysisCtrl.bug.ts
static/analysis.css

Probably not done well, but I am trying.

Flip evaluation bar when board is flipped #1438

---

static/blogs/Bughouse Chess.md
static/blogs/Halloween Update.md
static/blogs/Late Summer Update.md
static/blogs/Variant Design Contest.md

I used https://wiki.creativecommons.org/wiki/Recommended_practices_for_attribution#This_is_a_great_attribution for the format.

Add licenses to blog images

---

README.md

I coreeted some mistakes in ReadMe

Correct some mistakes
