gbtami/pychess-variants

server/fairy.py

The "Copy UCI/USI" button currently reports the starting SFEN for shogi also for minishogi games, e.g., see https://pychess-variants.herokuapp.com/AziKI68u.

Fix minishogi start SFEN for copy UCI/USI button

---

server/utils.py

Stalemate is scored as a win for the stalemating player in shogi variants. See https://pychess-variants.herokuapp.com/F4Krs90b for an example of the bug.
Note: This code implicitly also already covers minixiangqi in case it will be added.
Ultimately, I think it would be better to let pyffish decide on the game result, but for now I chose a minimal fix.

Fix stalemate adjudication for shogi

---

client/clock.ts

Behavior observed at https://www.twitch.tv/videos/541288181?t=0h20m35s
When rounding up to 0:10.0 (e.g., with 9999 milliseconds) 0:010.0 was displayed instead.

Remove leading zero when rounding up clock time

---

static/preview.css
static/site.css

At least until we have a better solution or a new settings panel, this could be a (temporary) fix for games which have more than 5 sets of pieces/boards. Also, the zoom slider is centered in the box with a tiny "margin" instead of displaying it from edge to edge.

Fix board/piece icon overflow in the settings panel

---

client/settings.ts
static/site.css

Except for shogi, like I mentioned it on Discord. This blurry scaling problem exists mostly in Chrome/Chromium (and I guess in other Chromium-based browsers). It seems to me that Firefox scales SVG better (not as blurry).
Side note: in Firefox we can click on the slider and use the mouse wheel to zoom in/out (smoother than dragging the slider thumb). This doesn't work in Chrome/Chromium, but I guess it's a browser feature.

Fix zoom slider's blurry scale

---

README.md

by using `yarn gulp prod` instead of `gulp prod` you make sure that people always run the dependency version specified by the project instead of running with their global gulp's version.
It also doesn't work if you don't have gulp installed globally on your machine.

Sugestion: Update Project setup

---

client/analysisCtrl.ts
client/movelist.ts

This fixes the issue where variations in the analysis board are always registered as variations of the first move. Also, it makes it possible to append new moves at the end of the move list, and to navigate the move list, even inside variations, with the step buttons. Only one variation at a time is supported.

Analysis board navigation

---

README.md
md2html-mac.sh
package.json

@gbtami I only tested this in Mac (and it's working). I tried to keep Linux's implementation as it was and defaulted to the Linux setup for any O.S. other than Mac. But as I refactored the script a bit, I'd like you to test it on Linux before accepting this PR, in case I broke something 😬 
I rewrote `md2html.sh` a bit, abstracting some functions to avoid duplication. By detecting the OS first, then we load `mac.sh` or `linux.sh` with specific commands for each. It's not the best implementation because many things are the same, but this way at least they can be versioned apart if any new difference appears, and also `md2html.sh` is simpler and hopefully easier to maintain 🤞 
--[ commit message: ]-----
MacOS comes usually with old bash and sh versions, so some commands are
not exactly as in …

Fix project dev setup for MacOS

---

static/round.css

Note that since I didn't fix my login problem in local I haven't tested the crosstable (but it should work).
--[commit message]------------------------
They are distractions as well, so we should hide them too, same as
lichess does.
We hide each "move" instead of the whole #movelist to hide all the moves
but not the container that includes, for example the result of the game.
We don't hide the rematch/analysis buttons either. Again, same as lichess.

Hide crosstable and move-list in zen mode

---

client/promotion.ts
client/roundCtrl.ts

https://github.com/gbtami/pychess-variants/issues/478
So far dealing only with discarding autoqueen when making a regular move, not a premove.
What do you think would be the more natural behaviour, to ask to choose a piece when making the premove (like on lichess), or when the premove actually fires (like here without autoqueen enabled)?

Support basic Ctrl autoqueen disable

---

README.md

does https:/ really needed? I don't think so cuz www.pychess.org redirects with https

Update Title in docs

---

client/i18n.ts
client/lobby.ts

#790 
I know those names appear in 2 contexts namely creating a seek and displaying already existing seeks, but the former already had call of _() https://github.com/gbtami/pychess-variants/blob/master/client/lobby.ts#L592

Make built in custom starting position names translatable

---

client/boardSettings.ts
client/chess.ts
client/editorCtrl.ts
client/material.ts
client/roundCtrl.ts

This reuses the logic of material.ts, so I refactored it. The material differences in-game should probably be tested.
It also reverts the Clear Board button to its original functionality.

Add "Fill Gote's Hand" button to the editor

---

client/roundCtrl.ts
server/clock.py

See #976 
These changes prevent a casual game from aborting due to not playing the first move in time by stopping the countdown. They also stop client from rendering expiration times in casual games.

Stop aborting casual games due to not making the first move in time

---

client/variants.ts
static/images/pieces/chennis/bBS_r.svg
static/images/pieces/chennis/bCF_r.svg
static/images/pieces/chennis/bFC_r.svg
static/images/pieces/chennis/bMN_r.svg
static/images/pieces/chennis/bNM_r.svg
static/images/pieces/chennis/bPR_r.svg
static/images/pieces/chennis/bRP_r.svg
static/images/pieces/chennis/bSB_r.svg
static/images/pieces/chennis/wBS_r.svg
static/images/pieces/chennis/wCF_r.svg
static/images/pieces/chennis/wFC_r.svg
static/images/pieces/chennis/wMN_r.svg
static/images/pieces/chennis/wNM_r.svg
static/images/pieces/chennis/wPR_r.svg
static/images/pieces/chennis/wRP_r.svg
static/images/pieces/chennis/wSB_r.svg
static/images/pieces/green/bK_r.svg
static/images/pieces/green/wK_r.svg
static/piece/chennis/chennis2.css
static/piece/chennis/chennis3.css
static/piece/chennis/chennis4.css
static/preview.css

I've included a set of flipped pieces, White and Black, of the standard Chennis two-piece "CBurnett" styled theme. I tested the pieces set locally, and it seemed to work correctly. A preview is attached below. I also swapped the location of the Merida style so it was better grouped.
Having a single color with orientation flipped to show piece ownership is how I made an over-the-board Chennis set, so I thought it would be useful to add them to the site. They are also more clear on the French and US Open courts if you choose the opposite color (otherwise one of promotion colors blends in with the background).

Add flipped Chennis piece sets

---

client/analysisCtrl.ts

2 bugs in analysis mode:
1. It when scrolling to previous move and then making a move on the board that is the same with the main line, it fails to detect it and starts a new variation instead of scrolling to next existing move - changed this.steps[this.ply - 1] to this.steps[this.ply]
2. Make 2 moves, scroll back once and start a new variation. Make it a long variation - say 10 moves. Scroll back to the 5th move of the variation and make a different move so it tries to erase the rest of the variation after that and append the new move. It will  fails on this same line, because of this.ply too large and outside of mainline steps list so it cannot make this check

Fixing 2 bugs about variations

---

static/site.css

**Changes**
I added a vertical scrollbar to the language and board settings in a responsive way so the scrollbar doesn't end short on devices with less viewport height. (Issue #987)
https://github.com/gbtami/pychess-variants/assets/126312812/ba7b3ea2-36a1-4afc-a97d-9d30480ecbc4

Fix Issue #987: Add scrollbar to settings dialog

---

static/site.css

The `.modal` scrollbar is not necessary as it just moves the "new game" panel up and down. It persists on viewports with shorter heights. I tested on Safari, Chrome, and Firefox.
https://github.com/gbtami/pychess-variants/assets/126312812/54ce4620-5c38-45cb-9768-2e3ff5b039b4
Removed Scrollbar
https://github.com/gbtami/pychess-variants/assets/126312812/afb14afe-a895-463d-81fe-71c59423f163

Remove Unnecessary Scrollbar

---

static/docs/3check960.md
static/docs/atomic960.md
static/docs/chess.md
static/docs/crazyhouse.md
static/docs/crazyhouse960.md
static/docs/es/chess.md
static/docs/es/crazyhouse.md
static/docs/es/placement.md
static/docs/fr/placement.md
static/docs/hu/chess.md
static/docs/hu/placement.md
static/docs/it/chess.md
static/docs/it/placement.md
static/docs/kingofthehill960.md
static/docs/placement.md
static/docs/pt/chess.md
static/docs/pt/placement.md
static/docs/zh/chess.md
static/docs/zh_CN/chess.md
static/docs/zh_TW/chess.md

**Chess**
* linked Pychess editor in text
**Crazyhouse**
* removed line break
**Placement**
* linked Chess Variants site's version of Placement Chess
* removed "see here, click here, etc" type of unnecessary link text
**English articles for 960 versions of 3check, atomic, crazyhouse, KOTH**
* added bullet points
* separated the two main rules and the castling rule 
(the same articles in other languages already have these changes)
I committed three times for one file because I made a mistake.

Variants Pages Minor Changes

---

static/site.css

The lobby tab markers are unaligned with the container and they briefly intersect when switching the tabs.
https://github.com/gbtami/pychess-variants/assets/126312812/a32d33d8-37e0-4db0-bf68-5d0d0cd9bd4b
https://github.com/gbtami/pychess-variants/assets/126312812/7045ee1e-aa87-408f-b41b-1d60bf881799
Also spacing

Align orange lobby tab markers

---

static/memory.css

* make header smaller
* align header
* prevent accidental highlighting of cards

Memory page changes

---

static/site.css

Shield icons are misaligned to the left
Shield icons are centered

Adjust shield icons placement in tournaments page

---

static/lobby.css

* fixed player counter link hitbox being wider than intended
* added color transition

Improve counter links

---

static/site.css

Separate new tournament box shadows from transition animation

---

static/site.css

* need div.guide to prevent it from affecting sidebar links

Allow styling of links in lists on variants pages

---

static/tournament.css

https://github.com/gbtami/pychess-variants/assets/126312812/ca713769-1c36-4390-bc26-259fd343ec04
https://github.com/gbtami/pychess-variants/assets/126312812/c58408ca-8b3a-45f3-9827-6eb1f8656a37
The problem was that the height of the button was increasing to adjust for the decrease in the bottom border width due to border-box box-sizing.

Improve tournament join button

---

static/site.css

Reduce top and bottom padding by 1/3 and remove margin-right that caused "KOTH 960" to take two lines. 
Before
After

Reduce padding for links to variants on small screens

---

static/variants.css

On mobile, videos will take up space on the side so there will be an x-scrollbar.

Prevent variants videos from overflowing

---

client/puzzleCtrl.ts

#1223
[Test Puzzle](https://www.pychess.org/puzzle/Kebky)
My PR only addresses the specific case of ".github.io" , but I don't think there are or will be other puzzle sources with long names.

Fix Issue #1223: Puzzle source breaks across multiple lines

---

static/profile.css

* Aligns players and their ratings
* Limits blue text hover to player names
Before:
After:

Tidy up profile game view

---

server/index.py
server/server.py

Currently, [invalid Pychess links](https://www.pychess.org/fadf) don't have a set `<title>`  so the `<title>` defaults to the page link. I think this happens because the `view` is never defined.
https://github.com/gbtami/pychess-variants/blob/f8a2527f003c78508d20844f55e87fca59bb2e35/server/index.py#L384-L387

Set title for 404 page

---

templates/profile.html

It doesn't make sense for there to be a link to someone's profile when the user is already on that page.

Remove self link from profile

---

static/site.css

Currently the bottom-borders are almost impossible to see.

Make border color separating game requests stronger

---

static/site.css

light mode: rgb(128) -> rgb(117)
<hr>
dark mode: rgb(128) -> rgb(140)
At least reach AA for now because AAA will require changing many other chat elements.

Increase chat time contrast

---

static/site.css

First part is changed, second part is what it looks like right now.
* stops blue text color hover effect
* makes entire list element part of link
https://github.com/gbtami/pychess-variants/assets/126312812/80f7f6d3-0af5-4d86-a832-56053b441d46

improve player search links

---

client/lobby.ts

Proposed Pychess upcoming tournament
Lichess upcoming tournament

Remove variant name from tournament description

---

static/site.css

Before
After
This is the only thing `--ct-current `is responsible for.

Increase visibility of faq questions in dark mode

---

static/lobby.css
static/site.css

Before:
https://github.com/gbtami/pychess-variants/assets/126312812/ef5e29c5-8779-44ea-ace9-ab2012540eb7
After:
https://github.com/gbtami/pychess-variants/assets/126312812/865403f6-af90-40e8-b429-bb162dfde79c
Errors only happen when 
viewport height < viewport width < 800

Partially fix tablet responsive design

---

static/site.css

https://github.com/gbtami/pychess-variants/assets/126312812/49ef741c-e3a4-4276-94f9-8c2512d95250
Right now the blog preview is forming rows of 2 and 1 or 3 rows of 1 depending on the viewport.

Limit blog preview rows

---

static/site.css

* moves border-radius from image to entire post card
* resets margin-right of post text that caused it to wrap early
* sets title and subtitle apart in distance and color
Light before
Light after
Dark before
Dark after

Improve blog preview 

---

static/site.css
static/videos.css

Add spotlight border radius and sidebar shadows

---

static/players.css

Before
After
For dark mode it doesn't really change.
I'm planning on simplifying stylesheets later as styling elements is getting really messy.

Fix light mode winners contrast

---

static/site.css

* Adds gray background to dropdown in dark mode
* Gives the main section link `color: var(--font-color)` when hovering to dropdown links
* dark mode dropdown links less gray (more contrast for respective mode)
https://github.com/gbtami/pychess-variants/assets/126312812/d09e831c-9f79-49c1-83b8-2582d6ac5826
https://github.com/gbtami/pychess-variants/assets/126312812/1452f4b3-9b21-47ba-a659-c5996a93ee57

Improve navbar colors in mouse interactions

---

static/docs/shatranj.md

fixing the typos in the second rule
in the second rule shown, "Stalemates" and "stealmated" have been modified to "Stalemate" and "stalemated" respectively

fixing typos in static/docs/shatranj.md

---

client/variants.ts

for convenience in playing the original variant that spawned chess
in chaturanga the kings do not face each other, the white king on the e-file and the black king on the d-file

add chaturanga as alternate start FEN

---

static/site.css

When the dialog is opened on viewports smaller than 800px
What the dialog looks like on larger viewports, specifically on Safari (seriously)
If you dont have Safari there are emulators that allow you to see it
Result

Fix dialog bugs on smaller viewport widths

---

.github/workflows/black.yml

Potential fix for [https://github.com/gbtami/pychess-variants/security/code-scanning/27](https://github.com/gbtami/pychess-variants/security/code-scanning/27)
To fix the issue, add a `permissions` block at the root level of the workflow file. This block will apply to all jobs in the workflow unless overridden by a job-specific `permissions` block. Since the linting job does not require write access, the permissions can be limited to `contents: read`. This ensures that the workflow adheres to the principle of least privilege.
---
_Suggested fixes powered by Copilot Autofix. Review carefully before merging._

Potential fix for code scanning alert no. 27: Workflow does not contain permissions

---

client/main.ts

Potential fix for [https://github.com/gbtami/pychess-variants/security/code-scanning/18](https://github.com/gbtami/pychess-variants/security/code-scanning/18)
To fix the issue, we need to sanitize or escape the untrusted data before using it in the URL. The best approach is to use a library or built-in function to encode the data as a URL component, ensuring that any special characters are properly escaped. This prevents malicious input from being interpreted as executable code.
Specifically:
1. Use `encodeURIComponent` to sanitize `searchInput.value` before concatenating it into the URL.
2. Ensure that `model["home"]` is a trusted value or sanitize it as well.
_Suggested fixes powered by Copilot Autofix. Review carefully before merging._

Potential fix for code scanning alert no. 18: DOM text reinterpreted as HTML

---

client/analysisCtrl.ts

In Duck Chess, the analysis board was not showing the arrow for the duck's move, only for the piece's move. This was because the code that generates the shapes for the analysis board was overwriting the arrow shape with the duck's shape.
This commit fixes the issue by appending the duck's shape to the array of shapes, instead of overwriting it. It also adds a check to ensure that the move string contains a duck move before attempting to draw the shape.

Fix: Arrows missing from duck chess analysis suggestions

---

client/editor/editorCtrl.ts
client/lobby.ts
server/routes.py
server/views/lobby.py

The "Play with machine" button in the board editor was incorrectly redirecting to a challenge page for the "Fairy-Stockfish" bot. This prevented users from starting a local game against the AI directly from the editor.
This commit fixes the issue by:
- Changing the redirection URL in `client/editor/editorCtrl.ts` to a new `/play/` endpoint.
- Adding a new route in `server/routes.py` to handle the `/play/` URL.
- Updating `client/lobby.ts` to recognize the new URL and trigger the "Play with AI" dialog.

Fix "Play with machine" from the editor

---

server/fishnet.py

Potential fix for [https://github.com/gbtami/pychess-variants/security/code-scanning/35](https://github.com/gbtami/pychess-variants/security/code-scanning/35)
To fix this, we need to remove or redact the API key (`key`) from the log message. Instead of logging the API key, we can log a less sensitive identifier such as the worker’s name (available from the `worker` variable assigned from `FISHNET_KEYS[key]`), or just a generic message without the key. This change should be made directly at line 259 in server/fishnet.py. No additional imports are needed, since we’re not introducing new functionality, just changing the logging argument to use a non-sensitive value already present in scope.
---
_Suggested fixes powered by Copilot Autofix. Review carefully before merging._

Potential fix for code scanning alert no. 35: Clear-text logging of sensitive information

---

client/main.ts

Potential fix for [https://github.com/gbtami/pychess-variants/security/code-scanning/30](https://github.com/gbtami/pychess-variants/security/code-scanning/30)
To fix the issue, we need to ensure that the `data-home` attribute value is sanitized or validated before being used. A simple and effective approach is to validate the `data-home` value against a whitelist of allowed URLs or ensure it conforms to a safe format (e.g., a valid URL). If the value is invalid, we can either reject it or replace it with a default safe value.
The fix involves:
1. Adding a validation function to check if the `data-home` value is a valid URL.
2. Sanitizing or replacing the `data-home` value in the `initModel` function before assigning it to `model["home"]`.
---
_Suggested fixes powered by Copilot Autofix. …

Potential fix for code scanning alert no. 30: DOM text reinterpreted as HTML

---

.github/workflows/web_tests.yml

Potential fix for [https://github.com/gbtami/pychess-variants/security/code-scanning/40](https://github.com/gbtami/pychess-variants/security/code-scanning/40)
To fix this problem, the workflow should have an explicit `permissions` block specified, ideally at the workflow (top) level, so that all jobs inherit the most restrictive permissions required. In the case of this workflow, the CI job does not require any write access; it is only reading code and performing tests. Thus, the minimal required permission is `contents: read`. The fix is to add a `permissions:` block with `contents: read` after the `name:` block and before or after the `on:` block (placing it just after `name:` is common and clear). No code or step changes are necessary; only the addition of this `permissions:` block. …

Potential fix for code scanning alert no. 40: Workflow does not contain permissions

---

client/cgCtrl.ts
client/document.ts
client/invite.ts
client/main.ts
client/url.ts
package.json
tsconfig.json
yarn.lock

The `yarn test` command was failing with a `SyntaxError: The requested module 'chessgroundx' does not provide an export named 'Chessground'`.
This error was caused by a side effect of having a `sanitizeURL` function in `client/main.ts`, which uses browser-specific APIs like `URL` and `window.location.origin`. This seemed to interfere with Jest's module resolution mechanism, specifically for the `chessgroundx` package.
The fix involves moving the `sanitizeURL` function to its own file, `client/url.ts`, and updating the imports accordingly. This isolates the function and prevents it from affecting the test environment in unexpected ways.
Additionally, the Jest configuration in `package.json` was improved to:
- Add a `moduleNameMapper` for the `@/` alias.
- Add `transformIgnorePatterns` to …

fix(jest): Resolve module resolution error in tests

---

static/COPYING.md

Similar to lichess and fairyground, this adds a COPYING.md file to collect all the copyright/credit info about our image and sound files in static/ and create a markdown table with links. This includes detailed research into the origins and licenses of the various piece sets.

Create COPYING.md to credit assets
